dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - storage-migration-ostbase
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8"
before_install:
  - sudo apt-get update 
  - sudo apt-get install nodejs 
  - sudo apt-get install npm  
  - sudo apt-get install software-properties-common
install: 
  - npm install 
before_script:
  - mkdir -p dynamodb
  - wget https://s3.ap-south-1.amazonaws.com/dynamodb-local-mumbai/dynamodb_local_latest.zip -O ./dynamodb/dynamodb_local_latest.zip
  - unzip ./dynamodb/dynamodb_local_latest.zip
  - nohup java -Djava.library.path=./dynamodb/DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &
script:  
  - node_modules/mocha/bin/mocha tests/mocha/services/dynamodb/* --timeout 10000 --exit
  - node_modules/mocha/bin/mocha tests/mocha/services/shard_management/* --timeout 10000 --exit
after_script:
  - kill $(ps aux | grep 'DynamoDBLocal.jar' | awk '{print $2}')