dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - review-changes-2805
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
env:
  global:
    - OS_CACHING_ENGINE=memcached
    - OST_MEMCACHE_SERVERS=127.0.0.1:11211
node_js:
  - "8"
services:
  - memcached
before_install:
  - sudo apt-get update 
  - sudo apt-get install nodejs 
  - sudo apt-get install npm  
install:
  - npm install 
before_script:
  - mkdir -p dynamodb
  - wget https://s3.ap-south-1.amazonaws.com/dynamodb-local-mumbai/dynamodb_local_latest.zip -O ./dynamodb/dynamodb_local_latest.zip
  - unzip ./dynamodb/dynamodb_local_latest.zip
  - mkdir -p dynamodb_instance_2
  - nohup java -Djava.library.path=./dynamodb/DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb &
  - nohup java -Djava.library.path=./dynamodb/DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -dbPath ./dynamodb_instance_2 -port 8001 &
script:
  - node_modules/mocha/bin/mocha tests/mocha/services/dynamodb/* --timeout 10000 --exit
after_script:
  - kill $(ps aux | grep 'DynamoDBLocal.jar' | awk '{print $2}')
  - rm -rf dynamodb